### ISSUE TITLE
How does this repo relate to build.webmaker.org repo?

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/book.webmaker.org#10]
I ask b/c there are some relevant issues still in https://github.com/mozilla/build.webmaker.org/issues that we might want to port over, and perhaps even delete the other repo for clarity. Or vice versa. cc @OpenMatt

**Comment by OpenMatt** [comment]
we're phasing out build.webmaker.org and replacing it w. build.mozillafoundation.org. let's get a first iteration of the new site up and then we can review the old issues to see which we may want to port over?

**Comment by cassiemc** [comment]
Sounds good
