### ISSUE TITLE
Update links on mofo.build

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/book.webmaker.org#5]
@cadecairos: Thanks for moving build.webmaker.org to mofo.build

Can you update the headers and links in the left-hand nav, as per this spreadsheet?
https://docs.google.com/spreadsheets/d/1PCq0bZbLq8smIh9YF8EmZIrWSHqqwXfMt9mfjgGN7QQ/edit

**Comment by OpenMatt** [comment]
@cadecairos are you able to get this done this week, you think? were hoping to have updates completed by Jan 25, in time for our first staff meeting

**Comment by cadecairos** [comment]
I can make these changes, I think.

I'm not sure if we will have SSL up in time. I'm unfamiliar with the processes required to transfer domain ownership to Mozilla, so I don't know how long that will take. 

It also seems that trying to sign in on mofo.build sends you back to the SSL secured build.webmaker.org domain.

**Comment by cadecairos** [comment]
@OpenMatt I'm having trouble finding the links in the spreadsheet linked above. can you updated it with the file names where the links are?

**Comment by OpenMatt** [comment]
The links are new. I'd like to replace the links that are there with the new set of links in the spreadsheet.

**Comment by OpenMatt** [comment]
Using "Strategy, Goals and Plan" as the headers

**Comment by OpenMatt** [comment]
@cadecairos how you doing on this one? We'd like to have the page updated in time for the Monday staff meeting. Doable?

**Comment by OpenMatt** [comment]
I just merged https://github.com/MozillaFoundation/Build-and-Book/pull/8

**Comment by cadecairos** [comment]
@OpenMatt I'll try to get it up for review today.

**Comment by cadecairos** [comment]
I'm having trouble running this app locally, but I'll keep trying.

**Comment by OpenMatt** [comment]
maybe @davidascher can help, since he created it initially

**Comment by OpenMatt** [comment]
cade says:
It's mostly just figuring out what firebase and github credentials it needs
cause it errors out on launch if it's not set right

**Comment by cadecairos** [comment]
@OpenMatt @davidascher I've got it working.

unfortunately, some of the items in the list are too long to fit in the nav area: 
![screenshot_20160120_171710](https://cloud.githubusercontent.com/assets/438003/12464959/c1e9e6be-bf99-11e5-9f15-687f8dd017ce.png)

**Comment by OpenMatt** [comment]
Great thanks Chris. I'll take another pass at the copy.

**Comment by cadecairos** [comment]
@OpenMatt I can also widen it by ~80px

**Comment by OpenMatt** [comment]
@cadecairos is this on staging somewhere where I can play with it / have a look? Or just running locally? 
if just local, can you post a screen grab of the entire page here?
