### ISSUE TITLE
Move book.webmaker.org to book.mofo.build

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/book.webmaker.org#7]
Move this http://book.webmaker.org/

to a new URL like:

book.mofo.build

**Comment by OpenMatt** [comment]
@cadecairos any status update on this one?

**Comment by OpenMatt** [comment]
cc @davidascher since he set this up for us initially

**Comment by OpenMatt** [comment]
@cadecairos are you able to do this as well?

**Comment by cadecairos** [comment]
@OpenMatt 

https://build.mozillafoundation.org/ is up and running.

working on https://book.mozillafoundation.org/ - need to put some credentials in place, and modify the travis deploy, but ran out of time today.

**Comment by cadecairos** [comment]
I should say that build will also need some changes to github oath, so it redirects to the right host. It currently redirects to build.webmaker.org

**Comment by cadecairos** [comment]
In order to get the deployment of build working, I need access to whatever firebase app we're using for it.

@davidascher Do you have these or know who does?

I've already used the mofo-devops github account to register oauth credentials for the new domain.

**Comment by davidascher** [comment]
Yup, @cadecairos just hit me up on chat and I can transfer credentials to you / whatever is needed.  @simonwex do we have a mofo firebase account?

**Comment by OpenMatt** [comment]
@cadecairos I believe this is now complete? can you update or close?

**Comment by cadecairos** [comment]
The move is basically done. I still need to update DNS settings to either remove or redirect build.webmaker.org and book.webmaker.org to the new domains. I'm working on a patch to remove github auth as well, which is nearly ready to ship.

**Comment by OpenMatt** [comment]
Thanks @cadecairos !
